version: "3.4"
services:
  enqueuer:
    build: ./enqueuer
    depends_on:
      - worker
      - redis
  worker:
    build: ./worker
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:alpine3.9
